---
title: "Tracking the development of apartment housing activity against public transport service provision in Melbourne: 2004-2022"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    logo: "logo.svg"
    theme: default
    orientation: columns
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(tidyr)
library(plotly)
library(sf)
library(leaflet)

```

<script>
$(document).ready(function() {
  $("#about").click();
});
</script>

```{r global}
# apartment, population and service numbers
all.data <- readRDS("./data.rds")

# details for input selectors
LGA.names <- all.data %>% filter(type == "LGA") %>% .$location %>% unique()
corridors.train <- all.data %>% filter(type == "Train") %>% .$location %>% unique()
corridors.tram <- all.data %>% filter(type == "Tram") %>% .$location %>% unique()
corridors.bus <- all.data %>% filter(type == "Bus") %>% .$location %>% unique()

# data for map
areas <- readRDS("./areas.rds")
walkable.catchments <- readRDS("./walkable catchments.rds")
apartments <- readRDS("./apartments.rds")


```

{.sidebar data-width=300}
----------------------------------------------------

<b>Data selection:</b>

```{r}

# selection of level of analysis area (Greater Melbourne, LGA, corridor)
selectInput("area", 
            HTML("Select an area type:
                 <a title='Area type may be Greater Melbourne, or a Local Government Area, or a corridor. Corridors are the stations or stops that make up a line or route, or a section of a line or route.'><sup> ?</sup></a>"),
            list("Greater Melbourne",
                 "Local Government Areas", 
                 `Corridors` = list("Train corridors", 
                                    "Tram corridors", 
                                    "Bus corridors")))

# conditional selection of LGA or corridor
conditionalPanel(
  condition = "input.area == 'Local Government Areas'",
  selectInput("location.lga", "Select a Local Government Area:", LGA.names)
)

conditionalPanel(
  condition = "input.area == 'Train corridors'",
  selectInput("location.train", "Select a train corridor:", corridors.train)
)

conditionalPanel(
  condition = "input.area == 'Tram corridors'",
  selectInput("location.tram", "Select a tram corridor:", corridors.tram)
)

conditionalPanel(
  condition = "input.area == 'Bus corridors'",
  selectInput("location.bus", "Select a bus corridor:", corridors.bus)
)
```

Select data to display:

```{r}

# data to display
# checkboxInput("apts", "Apartments", value = TRUE)
checkboxInput("apts", 
              HTML("Apartments
                   <a title='Dwellings classified as attached 4 storey or more (to 2016) or apartments (from 2017), and other developments with 100 dwellings per hectare or more.'><sup> ?</sup></a>"), 
              value = TRUE)

checkboxInput("pop", 
              HTML("Population
                   <a title='The population of the area shown as the 800m walkable catchment on the map.
• For Greater Melbourne and Local Government Areas, this is the population of the area within 800m walking distance of the public transport stops that are walkable from the apartments in those areas.
• For corridors, this is the population of the area within 800m of the stations or stops that make up the corridor, where those stations or stops have apartments within walking distance.'><sup> ?</sup></a>"), 
              value = TRUE)

checkboxInput("serv", 
              HTML("Annual services
                   <a title='The annual number of public transport services operating within 800m walking distance of the relevant apartments.'><sup> ?</sup></a>"), 
              value = TRUE)
checkboxInput("serv_capadj", HTML("Annual services, capacity adjusted
                   <a title='The annual number of public transport services operating within 800m walking distance of the relevant apartments, adjusted to account for changes in passenger carrying capacity.'><sup> ?</sup></a>"), value = TRUE)

# show mode selections for Greater Melb/LGAs, where serv or serv_capadj selected
conditionalPanel(
  condition = "(input.area == 'Greater Melbourne' | input.area == 'Local Government Areas') &
              (input.serv | input.serv_capadj)",
  checkboxGroupInput("mode", "Select modes:",
                     c("Train", "Tram", "Bus *" =  "Bus"),
                     selected = c("Train", "Tram")),
  renderText("* if Bus is selected, only data from 2016 can be shown")
)

# show fixed mode for corridors, where serv or serv_capadj selected
conditionalPanel(
  condition = "input.area == 'Train corridors' & (input.serv | input.serv_capadj)",
  renderText("Mode: Train (selected corridor services only)"),
)

conditionalPanel(
  condition = "input.area == 'Tram corridors' & (input.serv | input.serv_capadj)",
  renderText(paste0("Mode: Tram (", input$location.tram, " services only)")),
)

conditionalPanel(
  condition = "input.area == 'Bus corridors' & (input.serv | input.serv_capadj)",
  renderText(paste0("Mode: Bus (", input$location.bus, " services only)")),
)

# automatic updating of mode input to match corridor selection
observeEvent(input$area, {
  if (input$area == "Train corridors")
    updateCheckboxGroupInput(session,  "mode", selected = "Train")
  else if (input$area == "Tram corridors")
    updateCheckboxGroupInput(session, "mode", selected = "Tram")
  else if (input$area == "Bus corridors")
    updateCheckboxGroupInput(session, "mode", selected = "Bus")
})

# ensure at least one dataset is always present (apartments as default)
observeEvent(c(input$apts, input$pop, input$serv, input$serv_capadj), {
  if (!input$apts && !input$pop && !input$serv && !input$serv_capadj)
    updateCheckboxInput(session, "apts", value = TRUE)
})

```

<br>

```{r}
# year selector
sliderInput("years", label = "Select years:",
            min = 2004, max = 2022, value = c(2004, 2022), step = 1, 
            sep = "", ticks = FALSE)

# minimum year must be 2016 for bus
observeEvent(c(input$mode, input$serv, input$serv_capadj), {
  if ("Bus" %in% input$mode & (input$serv | input$serv_capadj))
    updateSliderInput(session, "years", min = 2016)
})

observeEvent(c(input$mode, input$serv, input$serv_capadj), {
  if (!("Bus" %in% input$mode) | (!input$serv & !input$serv_capadj))
    updateSliderInput(session, "years", min = 2004)
})


```

<br>
<b>Information:</b>

```{r}
# text to be shown in information popups

about.text <- HTML("This dashboard displays results of a longitudinal study of the development of apartment housing against public transport service provision in Melbourne, Australia from 2004 to 2022. <br><br>

The dashboard shows results for Greater Melbourne as a whole, for local government areas within Greater Melbourne, and for train, tram and selected bus corridors within Greater Melbourne.  The information shown covers: <br>
• change in apartments by year from 2004, <br>
• change in population by year from 2004, and <br>
• change in public transport services by year from 2004 for train and tram services and from 2015 for bus. <br><br>

Two indicators are shown for public transport services: <br>
• ‘annual services’ - the raw number of services each year, and <br>
• ‘annual services, capacity adjusted’ - the number of services adjusted to account for changes in the passenger carrying capacity, which is particularly relevant for tram (and some train) services in Melbourne where larger vehicle types have been progressively introduced on some routes. <br><br>

The values shown on the chart are aligned so that they are all indexed to 100 in the starting year. <br><br>

The results can be used to help assess whether policy aims of integrating land use with public transport service provision are being achieved, and to assess gaps in equity of service provision across the city.
")

data.text <- HTML("Data sources: <br>
•	annual apartments: Victorian Department of Transport and Planning (DTP). <br>
•	apartment baseline: Australian Bureau of Statistics 2006 census. <br>
•	train and tram service volumes and train capacities: DTP. <br> 
•	tram capacities: Yarra Trams. <br>
•	bus service volumes: Public Transport Victoria GTFS data. <br>
•	bus capacities: DTP and bus operators. <br><br>
  
'Apartments' are dwellings classified by DTP as 'attached 4 storey or more' (to 2016) or 'apartments' (from 2017), and other developments with 100 dwellings per hectare or more. <br><br>

[Currently, the apartment figures for 2022 only include apartments for the first half of the year. The remainder will be added once the relevant data is available.] <br><br>
  
'Corridors' are the stations or stops that make up a line or route, or section of a line or route. Corridors exclude areas in Central Melbourne. <br><br>

'Annual services' are the annual number of public transport services operating within 800m walking distance of the relevant apartments. <br><br>

‘Annual services, capacity adjusted’ are the annual services, adjusted to account for changes in passenger carrying capacity.  For example, if capacity of trams used on a tram route is increased by 50%, the capcity adjusted figure for the route is also be increased by 50%. <br><br>

If 'Greater Melbourne' or a Local Government Area is selected, all services of the selected modes are counted.  If a corridor is selected, only services of the selected mode and the selected line or route are counted. Where routes have changed, services are adjusted to include predecessor routes.<br><br>

'Walkable catchments' shown on the map are:<br>
•	for Greater Melbourne and Local Government Areas, places within 800m walking distance of the public transport stops that are walkable from the apartments in those areas.<br>
•	for corridors, places within 800m walking distance of the stations or stops that make up the corridor, where those statons or stops have apartments within their catchments.<br><br>
   
'Population' is the population of the walkable catchment. <br><br>

‘Years’ are Australian financial years ending 30 June. For example, ‘22’ is the financial year ending 30 June 2022. <br><br>

‘Growth’ figures are the change in value from the first to the last year for which data is shown, divided by the first year value, expressed as a percentage.
")

contact.text <- HTML("
<a href='https://cur.org.au/people/dr-chris-de-gruyter/' target='_blank'> <b>Chris De Gruyter</b>  </a> <br>
Centre for Urban Research, RMIT University, Melbourne, Australia <br>
Email: <a href='mailto:chris.degruyter@rmit.edu.au'> chris.degruyter@rmit.edu.au </a> <br><br>

<a href='https://cur.org.au/people/steve-pemberton/' target='_blank'> <b>Steve Pemberton</b> </a> <br>
Centre for Urban Research, RMIT University, Melbourne, Australia <br>
Email: <a href='mailto:steve.pemberton@rmit.edu.au'> steve.pemberton@rmit.edu.au </a> <br><br>

<a href='https://www.linkedin.com/in/eric-keys-94913b49/' target='_blank'> <b>Eric Keys</b> </a> <br>
Centre for Urban Research, RMIT University, Melbourne, Australia <br>
Email: <a href='mailto:eric.keys2@rmit.edu.au'> eric.keys2@rmit.edu.au </a> 
<br><br>

<a href='https://cur.org.au/project/packed-like-sardines-impacts-of-the-apartment-boom-on-public-transport-in-australian-cities/'> <b>Project website</b> </a>
")

# popup for 'about this dashboard' information
actionButton("about", "About this dashboard",
             class="btn btn-primary btn-sm btn-block",
             style="border-radius: 5px;")

observeEvent(input$about, {
  showModal(modalDialog(
    title = "About this dashboard",
    about.text,
  easyClose = TRUE,
  footer = modalButton("Close")
  ))
})

# popup for data information
actionButton("info", "Data information",
             class="btn btn-primary btn-sm btn-block",
             style="border-radius: 5px;")

observeEvent(input$info, {
  showModal(modalDialog(
    title = "Data information",
    data.text,
    easyClose = TRUE,
    footer = modalButton("Close")
  ))
})

# popup for contact information
actionButton("contact", "Contact",
             class="btn btn-primary btn-sm btn-block",
             style="border-radius: 5px;")

observeEvent(input$contact, {
  showModal(modalDialog(
    title = "Contact",
    contact.text,
    easyClose = TRUE,
    footer = modalButton("Close")
  ))
})


```



Column {data-width=600}
-----------------------------------------------------------------------

###

```{r}
# data for plot
data <- reactive({
  if (input$area == "Greater Melbourne") {
    filtered_data <- all.data %>%
      filter(location == "Greater Melbourne")
  } else if (input$area == "Local Government Areas") {
    filtered_data <- all.data %>%
      filter(location == input$location.lga)
  } else if (input$area == "Train corridors") {
    filtered_data <- all.data %>%
      filter(location == input$location.train)
  } else if (input$area == "Tram corridors") {
    filtered_data <- all.data %>%
      filter(location == input$location.tram)
  } else if (input$area == "Bus corridors") {
    filtered_data <- all.data %>%
      filter(location == input$location.bus)
  }
  
  # filter to relevant years
  filtered_data <- filtered_data %>%
    filter(Year >= input$years[1] & Year <= input$years[2])
  
  # Sum the selected services
  modes_selected <- input$mode
  
  filtered_data <- filtered_data %>%
    mutate(service = 0,
           service.capadj = 0)
  
  for (mode in modes_selected) {
    capadj_column <- paste0(mode, ".capadj")
    filtered_data <- filtered_data %>%
      mutate(service = service + !!sym(mode),
             service.capadj = service.capadj + !!sym(capadj_column))
  }

  # Extract the bases (the fixed minimum input year; but may be first available
  # year for services that don't start until a different year)
  apt.base <- filtered_data %>% filter(Year == min(Year)) %>% pull(Apartments)
  pop.base <- filtered_data %>% filter(Year == min(Year)) %>% pull(Population)
  
  serv.base <- filtered_data %>% 
    filter(service > 0) %>%
    filter(Year == min(Year)) %>%
    pull(service)
  
  serv_capadj.base <- filtered_data %>% 
    filter(service.capadj > 0) %>%
    filter(Year == min(Year)) %>% 
    pull(service.capadj)
  
  return(list(filtered_data = filtered_data, 
              apt.base = apt.base, 
              pop.base = pop.base,
              serv.base = serv.base,
              serv_capadj.base = serv_capadj.base))
})



renderPlotly({
  data <- data()
  
  # ranges for y axis (excluding 0s in service or service.capadj)
  apt.values <- data$filtered_data$Apartments
  pop.values <- data$filtered_data$Population
  serv.values <- data$filtered_data$service
  serv_capadj.values <- data$filtered_data$service.capadj
  # lowest non-zero values if any, or else 100
  min.apt <- ifelse(max(apt.values) > 0,
                    min(apt.values[apt.values > 0]) / data$apt.base * 100, 
                    100)
  min.pop <- ifelse(max(pop.values) > 0,
                    min(pop.values[pop.values > 0]) / data$pop.base * 100, 
                    100)
  min.serv <- ifelse(max(serv.values) > 0,
                     min(serv.values[serv.values > 0]) / data$serv.base * 100, 
                     100)
  min.serv_capadj <- ifelse(max(serv_capadj.values) > 0,
                            min(serv_capadj.values[serv_capadj.values > 0]) / data$serv_capadj.base * 100, 
                            100)
  # min and max for y axis
  min_y <- min(min.apt, min.pop, min.serv, min.serv_capadj)
  max_y <- max(apt.values / data$apt.base * 100,
               pop.values / data$pop.base * 100,
               serv.values / data$serv.base * 100,
               serv_capadj.values / data$serv_capadj.base * 100)
  
  # Create an empty plot
  p <- plot_ly()
  
  # Add a blank trace to ensure the legend is always present
  p <- p %>%
    add_trace(x = numeric(0), y = numeric(0), 
              type = "scatter", mode = "none", 
              name = "Legend Placeholder",
              showlegend = TRUE)
  
  
  if (input$apts) {
    p <- p %>%
      add_trace(data = data$filtered_data %>%
                  mutate(index = Apartments / data$apt.base * 100,
                         change = index - 100,
                         changetext = case_when(
                           Year == min(Year) ~ paste0("Apartments: ", 
                                               format(round(Apartments), 
                                                      big.mark = ",", nsmall = 0)), 
                           change > 0 ~ paste0("Apartments: ", 
                                               format(round(Apartments), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: +", 
                                               format(round(change, 1), nsmall = 1), "%"),
                           change < 0 ~ paste0("Apartments: ", 
                                               format(round(Apartments), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: ",
                                               format(round(change, 1), nsmall = 1), "%"),
                           change == 0 ~ paste0("Apartments: ",
                                                format(round(Apartments), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                                "Change since starting year: 0%"))),
                x = ~ Year, y = ~ Apartments / data$apt.base * 100, 
                type = "bar",
                marker = list(color = "#f2f2f2",
                              line = list(color = "#cccccc", width = 0.5)),
                name = "Apartments",  # Legend label
                customdata = ~ changetext,
                hovertemplate = "%{customdata}<extra></extra>"
                )
  }
  
  if (input$pop) {
    p <- p %>%
      add_trace(data = data$filtered_data %>%
                  mutate(index = Population / data$pop.base * 100,
                         change = index - 100,
                         changetext = case_when(
                           Year == min(Year) ~ paste0("Population within 800m walking distance: ", 
                                               format(round(Population), 
                                                      big.mark = ",", nsmall = 0)), 
                           change > 0 ~ paste0("Population within 800m walking distance: ", 
                                               format(round(Population), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: +", 
                                               format(round(change, 1), nsmall = 1), "%"),
                           change < 0 ~ paste0("Population within 800m walking distance: ", 
                                               format(round(Population), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: ",
                                               format(round(change, 1), nsmall = 1), "%"),
                           change == 0 ~ paste0("Population within 800m walking distance: ",
                                                format(round(Population), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                                "Change since starting year: 0%"))),
                x = ~ Year, y = ~ index,
                type = "scatter", mode = "lines+markers",
                marker = list(color = "#6A3D9A", size = 8, symbol = "square"),
                line = list(color = "#6A3D9A", width = 2),
                name = "Population within 800m walking distance",  # Legend label
                customdata = ~ changetext,
                hovertemplate = "%{customdata}<extra></extra>")
  }
  
  if (input$serv & length(input$mode > 0)) {
    p <- p %>%
      add_trace(data = data$filtered_data %>% 
                  filter(service > 0) %>%
                  mutate(index = service / data$serv.base * 100,
                         change = index - 100,
                         changetext = case_when(
                           Year == min(Year) ~ paste0("Annual services: ", 
                                               format(round(service), 
                                                      big.mark = ",", nsmall = 0)), 
                           change > 0 ~ paste0("Annual services: ", 
                                               format(round(service), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: +", 
                                               format(round(change, 1), nsmall = 1), "%"),
                           change < 0 ~ paste0("Annual services: ", 
                                               format(round(service), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: ",
                                               format(round(change, 1), nsmall = 1), "%"),
                           change == 0 ~ paste0("Annual services: ",
                                                format(round(service), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                                "Change since starting year: 0%"))),
                x = ~ Year, y = ~ index,
                type = "scatter", mode = "lines+markers",
                marker = list(color = "#FF7F00", size = 12),
                line = list(color = "#FF7F00", width = 4),
                name = "Annual services",  # Legend label
                customdata = ~ changetext,
                hovertemplate = "%{customdata}<extra></extra>")
  }
  
  if (input$serv_capadj & length(input$mode > 0)) {
    p <- p %>%
      add_trace(data = data$filtered_data %>% 
                  filter(service.capadj > 0) %>%
                  mutate(index = service.capadj / data$serv_capadj.base * 100,
                         change = index - 100,
                         changetext = case_when(
                           Year == min(Year) ~ paste0("Annual services, capacity adjusted: ", 
                                               format(round(service.capadj), 
                                                      big.mark = ",", nsmall = 0)), 
                           change > 0 ~ paste0("Annual services, capacity adjusted: ", 
                                               format(round(service.capadj), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: +", 
                                               format(round(change, 1), nsmall = 1), "%"),
                           change < 0 ~ paste0("Annual services, capacity adjusted: ", 
                                               format(round(service.capadj), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                               "Change since starting year: ",
                                               format(round(change, 1), nsmall = 1), "%"),
                           change == 0 ~ paste0("Annual services, capacity adjusted: ",
                                                format(round(service.capadj), 
                                                      big.mark = ",", nsmall = 0), "<br>",
                                                "Change since starting year: 0%"))),
                x = ~ Year, y = ~ index,
                type = "scatter", mode = "lines+markers",
                marker = list(color = "#33A02C", size = 6),
                line = list(color = "#33A02C", width = 2),
                name = "Annual services, capacity adjusted",  # Legend label
                customdata = ~ changetext,
                hovertemplate = "%{customdata}<extra></extra>")
  }
  
  # build string for title
  if (input$area == "Greater Melbourne") {
    titlestring1 <- ""
    titlestring2 <- input$area
  } else if (input$area == "Local Government Areas") {
    titlestring1 <- ""
    titlestring2 <- input$location.lga
  } else if (input$area == "Train corridors") {
    titlestring1 <- "Train corridor:"
    titlestring2 <- input$location.train
  } else if (input$area == "Tram corridors") {
    titlestring1 <- "Tram corridor:"
    titlestring2 <- input$location.tram
  } else if (input$area == "Bus corridors") {
   titlestring1 <- "Bus corridor:"
     titlestring2 <- input$location.bus
  }
  
  titlestring <- paste(titlestring1, titlestring2)
  
  # values for x-axis (last 2 digits of year only)
  x_values <- data$filtered_data$Year
  x_labels <- substring(x_values, 3, 4)
  
  p <- p %>%
    layout(title = list(text = titlestring,
                        x = 0.05),
           
           xaxis = list(
             tickvals = x_values,  # values always present
             ticktext = x_labels,
             title = "Financial Year ending 30 June"),
           yaxis = list(title = "Values indexed to starting year = 100<br>(Hover over for absolute values)",
                        range = list(min_y - 5, max_y + 5)),
           
           # legend centered at top
           legend = list(orientation = "h",  # show entries horizontally
                         xanchor = "center",  # use centre of legend as anchor
                         x = 0.5, y = 1)   # put legend in centre at top
           
     ) 
  
  p
})


```


Column {data-width=400}
-----------------------------------------------------------------------

```{css}
/* changes to make value box smaller: 90px, or 60px if screen <= 800px  */

.value-box {
  height: 90px;
}

.value-box .inner {
  padding: 5px;
  padding-left: 20px;
  padding-right: 20px;
}

.value-box .icon i {
 font-size: 70px;
}


@media (max-height: 800px) {

.value-box {
 height: 60px;
}

.value-box .inner {
  padding: 5px;
  padding-left: 20px;
  padding-right: 20px;
}

.value-box .value {
 font-size: 20px;
 margin: 0 0 0 0;
}

.value-box .p {
 margin: 0 0 0 0;
}

.value-box .icon i {
 top: 12px;
 font-size: 40px;
}

}

```

### Apartment change {.value-box}

```{r}

renderValueBox({
  # percentage change in 'apartments' from first to last year
  apt.start <- data()$filtered_data %>%
    filter(Year == min(Year)) %>%
    pull(Apartments)
  apt.end <- data()$filtered_data %>%
    filter(Year == max(Year)) %>%
    pull(Apartments)
  change <- round((apt.end - apt.start) / apt.start * 100, 1)

  # format output (allowing for no result because of zeros)
  if (is.na(change)) {
    valueText <- "-"
  } else if (is.numeric(change) & change > 0) {
    valueText <- paste("+", format(change, nsmall = 1), "%")
  } else if (is.numeric(change) & change < 0) {
    valueText <- paste("-", format(abs(change), nsmall = 1), "%")
  } else if (is.numeric(change) & change == 0) {
    valueText <- "0.0 %"
  } else {
    valueText <- "-"
  }
  
  valueBox(valueText, icon = "fa-building",
           color = ifelse(change < 0 | valueText == "-", "warning", "primary"))

})

```

### Population change {.value-box}

```{r}

renderValueBox({
  # percentage change in 'population' from first to last year
  pop.start <- data()$filtered_data %>%
    filter(Year == min(Year)) %>%
    pull(Population)
  pop.end <- data()$filtered_data %>%
    filter(Year == max(Year)) %>%
    pull(Population)
  change <- round((pop.end - pop.start) / pop.start * 100, 1)

  # format output (allowing for no result because of zeros)
  if (is.na(change)) {
    valueText <- "-"
  } else if (is.numeric(change) & change > 0) {
    valueText <- paste("+", format(change, nsmall = 1), "%")
  } else if (is.numeric(change) & change < 0) {
    valueText <- paste("-", format(abs(change), nsmall = 1), "%")
  } else if (is.numeric(change) & change == 0) {
    valueText <- "0.0 %"
  } else {
    valueText <- "-"
  }
  
  valueBox(valueText, icon = "fa-user",
           color = ifelse(change < 0 | valueText == "-", "warning", "primary"))

})

```
### Public transport change {.value-box}

```{r}

renderValueBox({
  # percentage change in 'service' from first to last year, excluding zero years
  serv.start <- data()$filtered_data %>%
    filter(service > 0) %>%
    filter(Year == min(Year)) %>%
    pull(service)
  # if all years zero, then set at zero
  if (length(serv.start) == 0) {
    serv.start <- 0
  }
  serv.end <- data()$filtered_data %>%
    filter(Year == max(Year)) %>%
    pull(service)
  change <- round((serv.end - serv.start) / serv.start * 100, 1)

  # format output (allowing for no result because of zeros)
  if (is.na(change)) {
    valueText <- "-"
  } else if (is.numeric(change) & change > 0) {
    valueText <- paste("+", format(change, nsmall = 1), "%")
  } else if (is.numeric(change) & change < 0) {
    valueText <- paste("-", format(abs(change), nsmall = 1), "%")
  } else if (is.numeric(change) & change == 0) {
    valueText <- "0.0 %"
  } else {
    valueText <- "-"
  }
  
  valueBox(valueText, icon = "fa-train",
           color = ifelse(change < 0 | valueText == "-", "warning", "primary"))
})

```
### Public transport change, capacity adjusted {.value-box}

```{r}

renderValueBox({
  # percentage change in 'service' from first to last year, excluding zero years
  serv_capadj.start <- data()$filtered_data %>%
    filter(service.capadj > 0) %>%
    filter(Year == min(Year)) %>%
    pull(service.capadj)
  # if all years zero, then set at zero
  if (length(serv_capadj.start) == 0) {
    serv_capadj.start <- 0
  }
  serv_capadj.end <- data()$filtered_data %>%
    filter(Year == max(Year)) %>%
    pull(service.capadj)
  change <- round((serv_capadj.end - serv_capadj.start) / serv_capadj.start * 100, 1)

  # format output (allowing for no result because of zeros)
  if (is.na(change)) {
    valueText <- "-"
  } else if (is.numeric(change) & change > 0) {
    valueText <- paste("+", format(change, nsmall = 1), "%")
  } else if (is.numeric(change) & change < 0) {
    valueText <- paste("-", format(abs(change), nsmall = 1), "%")
  } else if (is.numeric(change) & change == 0) {
    valueText <- "0.0 %"
  } else {
    valueText <- "-"
  }
  
  valueBox(valueText, icon = "fa-train",
           color = ifelse(change < 0 | valueText == "-", "warning", "primary"))
})


```


### 

```{css}
/* symbols required for map legend*/

    .legend {
      background-color: rgba(255, 255, 255, 0.6);
      border-radius: 3px;
    }
    .legend-item {
      display: flex;
      align-items: center;
    }
    .legend-symbol-container {
      width: 20px;
      height: 20px;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-right: 3px;
    }
    .legend-symbol-point {
      width: 5px;
      height: 5px;
      border-radius: 50%;
    }
    .legend-symbol-square {
      width: 10px;
      height: 10px;
      border-radius: 50%;
    }
    .area-symbol {
      background-color: transparent;
      border: 3px solid black;
      border-radius: 3px;
    }
    .catchment-symbol {
      background-color: rgba(231, 41, 138, 0.1);
      border: 2px solid #e7298a;
      border-radius: 3px;
    }
    .apartments-symbol {
      background-color: rgba(0, 0, 255, 0.65);
      width: 10px;
      height: 10px;
      border: 2px solid #0000ff;
      border-radius: 50%;
    }
     .other-apartments-symbol {
      background-color: rgba(44, 123, 182, 0.65);
      width: 10px;
      height: 10px;
      border: 2px solid #2c7bb6;
      border-radius: 50%;
    }


```


```{r}

display.polygons <- reactive({
  if (input$area == "Greater Melbourne") {
    area <- areas %>% filter(name == input$area)
    catchment <- walkable.catchments %>% filter(name == input$area)
  } else if (input$area == "Local Government Areas") {
    area <- areas %>% filter(name == input$location.lga)
    catchment <- walkable.catchments %>% filter(name == input$location.lga)
  } else if (input$area == "Train corridors") {
    area <- areas %>% filter(name == input$area)  # returns empty row
    catchment  <- walkable.catchments %>% filter(name == input$location.train)
  } else if (input$area == "Tram corridors") {
    area <- areas %>% filter(name == input$area)  # returns empty row
    catchment  <- walkable.catchments %>% filter(name == input$location.tram)
  } else if (input$area == "Bus corridors") {
    area <- areas %>% filter(name == input$area)  # returns empty row
    catchment <- walkable.catchments %>% filter(name == input$location.bus)
  }
  return(list(area = area, catchment = catchment))
})


renderLeaflet({
  area <- display.polygons()$area
  catchment <- display.polygons()$catchment
  if (input$area == "Local Government Areas") {
    display.apartments <- st_intersection(apartments, display.polygons()$area)
  } else {
    display.apartments <- st_intersection(apartments, display.polygons()$catchment)
  }
  selected.year.display.apartments <- display.apartments %>%
    filter(year_comp >= input$years[1] & year_comp <= input$years[2])
  other.year.display.apartments <- display.apartments %>%
    filter(year_comp < input$years[1] | year_comp > input$years[2])
  
  # 'area' section of legend (Greater Melbourne and LGAs only)
  if (input$area == "Greater Melbourne") {
    html_legend <- paste0('
    <div class="legend">
      <div class="legend-item">
        <div class="legend-symbol-container">
          <div class="legend-symbol-square area-symbol"></div>
        </div>',
        input$area,
      '</div>
    ', sep = "")
  } else if (input$area == "Local Government Areas") {
    html_legend <- paste('
    <div class="legend">
      <div class="legend-item">
        <div class="legend-symbol-container">
          <div class="legend-symbol-square area-symbol"></div>
        </div>', 
        input$location.lga, 
      '</div>
    ', sep = "")
  } else {
    html_legend <- '<div class="legend">'
  }
  
  # 'apartments' section of legend
  html_legend <- paste0(
    html_legend, '
      <div class="legend-item">
        <div class="legend-symbol-container">
          <div class="legend-symbol-point apartments-symbol"></div>
        </div>
        Apartments ', input$years[1], ' to ', input$years[2], ' 
      </div>
  ', sep = "")
  
  # 'other apartments' section of legend
  if (input$years[1] > 2004 | input$years[2] < 2022) {
    html_legend <- paste0(
      html_legend, '
        <div class="legend-item">
          <div class="legend-symbol-container">
            <div class="legend-symbol-point other-apartments-symbol"></div>
          </div>
          Other apartments 
        </div>
    ', sep = "")
  }
  
# 'catchment' section of legend
  html_legend <- paste0(
    html_legend, '
      <div class="legend-item">
        <div class="legend-symbol-container">
          <div class="legend-symbol-square catchment-symbol"></div>
        </div>
        800m walkable catchments
      </div>
    </div>
  ', sep = "")
  

  leaflet() %>%
    addTiles() %>%
    addPolygons(data = area, color = "black", weight = 3, opacity = 1, 
                fillColor = "transparent") %>%
    addPolygons(data = catchment, color = "#e7298a", weight = 2, opacity = 1,
                fillColor = "#e7298a", fillOpacity = 0.1) %>%
    addCircleMarkers(
      data = other.year.display.apartments, 
      radius = ~sqrt(hi_dens_dwel) / 2,
      color = "#2c7bb6",
      weight = 2,
      opacity = 1, 
      fillColor = "#2c7bb6",
      fillOpacity = 0.65,
      popup = ~paste("<b>", display_name, "</b><br>",
                     "No of apartments:", hi_dens_dwel, "<br>",
                     "Year constructed:", year_comp, "<br>")) %>% 
     addCircleMarkers(
      data = selected.year.display.apartments, 
      radius = ~sqrt(hi_dens_dwel) / 2,
      color = "#0000ff",
      weight = 2,
      opacity = 1, 
      fillColor = "#0000ff",
      fillOpacity = 0.65,
      popup = ~paste("<b>", display_name, "</b><br>",
                     "No of apartments:", hi_dens_dwel, "<br>",
                     "Year constructed:", year_comp, "<br>")) %>% 
    addControl(html = html_legend, position = "topright") %>%
    addScaleBar(position = "bottomleft", options = scaleBarOptions(imperial = FALSE))
})



```

